# Generated by Django 3.2.7 on 2022-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20220106_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
