# Generated by Django 2.1 on 2022-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20220205_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo1', models.ImageField(upload_to='')),
                ('logo2', models.ImageField(upload_to='Exhibition')),
                ('image1', models.ImageField(upload_to='Exhibition')),
                ('image2', models.ImageField(upload_to='Exhibition')),
                ('image3', models.ImageField(upload_to='Exhibition')),
                ('image4', models.ImageField(upload_to='Exhibition')),
                ('image5', models.ImageField(upload_to='Exhibition')),
                ('video', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('question', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
